# Generated by Django 5.2.4 on 2025-07-05 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_remove_task_category_task_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='contextentry',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='context_attachments/'),
        ),
        migrations.AddField(
            model_name='task',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='task_attachments/'),
        ),
    ]
