# Generated by Django 5.2.4 on 2025-07-06 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_contextentry_attachment_task_attachment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contextentry',
            name='attachment',
        ),
        migrations.RemoveField(
            model_name='task',
            name='attachment',
        ),
    ]
